// Generated by CoffeeScript 1.9.1
var Encoder;

(Encoder = (function() {
  function Encoder() {}

  Encoder.prototype.setMessage = function() {
    return this.message = $('#message').val();
  };

  Encoder.prototype.getPassword = function() {
    return this.password = prompt("Enter encoding key");
  };

  Encoder.prototype.setUrl = function() {
    var e;
    e = this.encrypt();
    return this.encryptedUrl = window.location.href + 'decode.html?' + this.encrypt();
  };

  Encoder.prototype.replaceMessageWithUrl = function() {
    var msg;
    msg = "Your encrypted message is\n\n" + this.encryptedUrl;
    return $('#message').val(msg);
  };

  Encoder.prototype.encrypt = function() {
    return CryptoJS.AES.encrypt(this.message, this.password);
  };

  Encoder.prototype.decrypt = function(cypher, pass) {
    return CryptoJS.AES.decrypt(cypher, pass).toString(CryptoJS.enc.Utf8);
  };

  Encoder.prototype.protect = function() {
    this.setMessage();
    this.getPassword();
    this.setUrl();
    return this.replaceMessageWithUrl();
  };

  return Encoder;

})())();
