// Generated by CoffeeScript 1.9.1
var Page;

(Page = (function() {
  function Page() {
    var _encoder;
    this.encoder = new Encoder();
    _encoder = this.encoder;
    $('#encrypt').click(function() {
      return _encoder.protect();
    });
    $('#decrypt').click(function() {
      var cypher, password;
      password = prompt('What is the pass phrase?');
      cypher = window.location.href.replace('http://localhost:4000/decode.html?', '');
      return $('#decodeMsg').html(_encoder.decrypt(cypher, password));
    });
  }

  return Page;

})())();
